version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  nextjs:
    build: ./
    ports:
      - '5432:5432'
  nginx:
    build: ./nginx
    ports:
      - 80:80

  # web:
  #   image: nginx
  #   restart: always
  #   volumes:
  #   - ./templates:/etc/nginx/templates
  #   ports:
  #   - "8080:80"
  #   environment:
  #   #  - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80
volumes:
  db:
    driver: local
